load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

MINGW_RUNTIME = ["//toolchain:mingw_runtime"]

cc_test(
    name = "structures_test",
    srcs = ["test_structures.cpp"],
    data = MINGW_RUNTIME,
    deps = [
        "//include:orderly_chaos_lib",
        "@com_google_googletest//:gtest",
    ],
)

cc_test(
    name = "limit_tree_test",
    srcs = ["test_limit_tree.cpp"],
    data = MINGW_RUNTIME,
    deps = [
        "//include:orderly_chaos_lib",
        "@com_google_googletest//:gtest",
    ],
)

cc_test(
    name = "limit_order_book_test",
    srcs = ["test_limit_order_book.cpp"],
    data = MINGW_RUNTIME,
    deps = [
        "//include:orderly_chaos_lib",
        "@com_google_googletest//:gtest",
    ],
)
