load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "orderly_chaos_lib",
    hdrs = glob(["*.hpp"]),
    includes = ["."],
    deps = [
        "//vendor/binary-search-tree:binary_search_tree",
        "//vendor/doubly-linked-list:doubly_linked_list",
        "//vendor/robin-map:robin_map",
    ],
)
